version: '2'
services:    
    redis:
       image: 'redis:5-alpine'
       container_name: redis
       command: redis-server
       ports:
        - '6379:6379'
       volumes:
         - 'redis:/data'
    sidekiq:
      depends_on:
        - 'redis'
      build:
        context: .
        dockerfile: Dockerfile.sidekiq
      container_name: sidekiq
      #command: /bin/bash -l -c 'source /etc/profile.d/rvm.sh && bundle exec sidekiq'
      volumes:
        - '.:/remotive-jobs'
      environment:
        - REDIS_URL=redis://redis:6379/1     
    jobsearch: 
        build:
           context: .
           dockerfile: Dockerfile
        container_name: jobsearch
        depends_on:
          - 'sidekiq'
          - 'redis'
        volumes: 
           - ".:/remotive-jobs"
        command: /bin/bash -l -c 'source /etc/profile.d/rvm.sh && bundle install && bundle exec rails webpacker:install && rails db:migrate && rake assets:precompile && rm -fr /remotive-jobs/tmp/pids/server.pid && bundle exec rails server -b 0.0.0.0' 
        environment:
        - REDIS_URL=redis://redis:6379/1 
        ports: 
             - "3000:3000"

volumes:
  redis:
